apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dfgj47s6j-python
  janus-idp.io/tekton: dfgj47s6j-python
  backstage.io/kubernetes-id: dfgj47s6j-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dfgj47s6j-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
